package ROS2.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Action_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Argument_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new CapabilityProfileAnnotation_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Monitor_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Namespace_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Remappings_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new RequirementsProfileAnnotation_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Topic_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new TopicRef_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new CapabilityProfileAnnotation_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new RequirementsProfileAnnotation_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db56L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x31ec195a6838a2aeL), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db52L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db54L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x28eca1beb2f1bfe4L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db55L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x31ec195a68373327L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db53L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x28eca1beb2ec604cL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db52L), MetaIdFactory.conceptId(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x31ec195a68373327L)).seal();
}
