package ROS2.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class AddDefaultQoS_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public AddDefaultQoS_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:186844af-000e-4714-9838-4712fa7d54ad(ROS2.intentions)", "3969865063210514232"));
  }
  @Override
  public String getPresentation() {
    return "AddDefaultQoS";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.DefaultQoS$mx)) == null)) {
        return "Add default QoS profile to system";
      } else {
        return "Remove default QoS profile to system";
      }
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.DefaultQoS$mx)) == null)) {
        SNode defaultQoS = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x3717cb3de2d53f21L, "ROS2.structure.DefaultQoS"));
        SPropertyOperations.set(defaultQoS, PROPS.depth$KTms, 10);
        SPropertyOperations.set(defaultQoS, PROPS.deadline$ZtXz, Integer.MAX_VALUE);
        SPropertyOperations.set(defaultQoS, PROPS.lifespan$L1kY, Integer.MAX_VALUE);
        SPropertyOperations.set(defaultQoS, PROPS.lease$KUKy, Integer.MAX_VALUE);
        AttributeOperations.setAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.DefaultQoS$mx), defaultQoS);
      } else {
        AttributeOperations.setAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.DefaultQoS$mx), null);
      }
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return AddDefaultQoS_Intention.this;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DefaultQoS$mx = MetaAdapterFactory.getConcept(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x3717cb3de2d53f21L, "ROS2.structure.DefaultQoS");
  }

  private static final class PROPS {
    /*package*/ static final SProperty depth$KTms = MetaAdapterFactory.getProperty(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x3717cb3de2d53f21L, 0x3717cb3de2d53fa6L, "depth");
    /*package*/ static final SProperty deadline$ZtXz = MetaAdapterFactory.getProperty(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x3717cb3de2d53f21L, 0x3717cb3de2d54165L, "deadline");
    /*package*/ static final SProperty lifespan$L1kY = MetaAdapterFactory.getProperty(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x3717cb3de2d53f21L, 0x3717cb3de2d53fb3L, "lifespan");
    /*package*/ static final SProperty lease$KUKy = MetaAdapterFactory.getProperty(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x3717cb3de2d53f21L, 0x3717cb3de2d53facL, "lease");
  }
}
