package ROS2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a2a0a51b0w = new IconResource("TextIcon_1.png", IconContainer.class);
}
