package ROS2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptArgument = createDescriptorForArgument();
  /*package*/ final ConceptDescriptor myConceptCapabilityProfileAnnotation = createDescriptorForCapabilityProfileAnnotation();
  /*package*/ final ConceptDescriptor myConceptMonitor = createDescriptorForMonitor();
  /*package*/ final ConceptDescriptor myConceptNamespace = createDescriptorForNamespace();
  /*package*/ final ConceptDescriptor myConceptRemappings = createDescriptorForRemappings();
  /*package*/ final ConceptDescriptor myConceptRequirementsProfileAnnotation = createDescriptorForRequirementsProfileAnnotation();
  /*package*/ final ConceptDescriptor myConceptTopic = createDescriptorForTopic();
  /*package*/ final ConceptDescriptor myConceptTopicRef = createDescriptorForTopicRef();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0x218e40b475d44de8L, 0x83e6b31e4da8bceeL, "Component");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptArgument, myConceptCapabilityProfileAnnotation, myConceptMonitor, myConceptNamespace, myConceptRemappings, myConceptRequirementsProfileAnnotation, myConceptTopic, myConceptTopicRef);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Argument:
        return myConceptArgument;
      case LanguageConceptSwitch.CapabilityProfileAnnotation:
        return myConceptCapabilityProfileAnnotation;
      case LanguageConceptSwitch.Monitor:
        return myConceptMonitor;
      case LanguageConceptSwitch.Namespace:
        return myConceptNamespace;
      case LanguageConceptSwitch.Remappings:
        return myConceptRemappings;
      case LanguageConceptSwitch.RequirementsProfileAnnotation:
        return myConceptRequirementsProfileAnnotation;
      case LanguageConceptSwitch.Topic:
        return myConceptTopic;
      case LanguageConceptSwitch.TopicRef:
        return myConceptTopicRef;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "Action", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db56L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2517694108707314518");
    b.version(2);
    b.aggregate("feedback", 0x6be9d018b214af9bL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506dL).optional(true).ordered(true).multiple(false).origin("7775975036117364635").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForArgument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "Argument", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x31ec195a6838a2aeL);
    b.class_(false, false, false);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/3597278078448476846");
    b.version(2);
    b.property("original", 0x31ec195a6838a2afL).type(PrimitiveTypeId.STRING).origin("3597278078448476847").done();
    b.property("remapping", 0x31ec195a6838a2b1L).type(PrimitiveTypeId.STRING).origin("3597278078448476849").done();
    b.alias("argument remap");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCapabilityProfileAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "CapabilityProfileAnnotation", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db52L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2517694108707314514");
    b.version(2);
    b.associate("profile", 0x31ec195a68373325L).target(0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x75d27ff7603f6d14L).optional(false).origin("3597278078448382757").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMonitor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "Monitor", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db54L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2517694108707314516");
    b.version(2);
    b.aggregate("topics", 0x28eca1beb2ec604fL).target(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x28eca1beb2ec604cL).optional(true).ordered(true).multiple(true).origin("2948909696438526031").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNamespace() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "Namespace", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x28eca1beb2f1bfe4L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2948909696438878180");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRemappings() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "Remappings", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db55L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2517694108707314517");
    b.version(2);
    b.aggregate("remappings", 0x31ec195a6838a2b4L).target(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x31ec195a6838a2aeL).optional(false).ordered(true).multiple(true).origin("3597278078448476852").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequirementsProfileAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "RequirementsProfileAnnotation", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x31ec195a68373327L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/3597278078448382759");
    b.version(2);
    b.associate("requirementsProfile", 0x31ec195a68373328L).target(0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0xdbe2d924f785bbaL).optional(false).origin("3597278078448382760").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTopic() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "Topic", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db53L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2517694108707314515");
    b.version(2);
    b.aggregate("publishers", 0x6be9d018b217c257L).target(0x218e40b475d44de8L, 0x83e6b31e4da8bceeL, 0x303c12ef1bceee98L).optional(false).ordered(true).multiple(true).origin("7775975036117566039").done();
    b.aggregate("subscribers", 0x6be9d018b217c259L).target(0x218e40b475d44de8L, 0x83e6b31e4da8bceeL, 0x303c12ef1bceee98L).optional(false).ordered(true).multiple(true).origin("7775975036117566041").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTopicRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ROS2", "TopicRef", 0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x28eca1beb2ec604cL);
    b.class_(false, false, false);
    b.origin("r:1882f704-9bf3-465f-a74a-418192e19224(ROS2.structure)/2948909696438526028");
    b.version(2);
    b.associate("topic", 0x28eca1beb2ec604dL).target(0x73f2d64e927d48dcL, 0x89c7793f38431f94L, 0x22f0a573da97db53L).optional(true).origin("2948909696438526029").done();
    return b.create();
  }
}
